from __future__ import annotations

from backend.app.db.models.accounts import AccountListResponse, AccountRecord
from backend.app.db.models.player_characters import CharacterDetailMemoryRecord, CharacterDetailWeaponRecord, CharacterEquipRecord, CharacterEquipResonanceRecord, CharacterExtraInfoRecord, CharacterFashionRecord, CharacterManagementItemRecord, CharacterManagementListResponse, CharacterSkillInfoRecord, CharacterWeaponOverrunRecord, SetCharacterSupportResponse
from backend.app.db.models.player_equips import AddMemoryResponse, AddWeaponResponse, ClearWeaponsResponse, MemoryExtraInfoRecord, MemoryListResponse, UpdateWeaponOverrunRequest, UpdateWeaponRequest, WeaponExtraInfoRecord, WeaponItemRecord, WeaponListResponse, WeaponOverrunExtraInfoRecord, WeaponOverrunRecord, WeaponResonanceExtraInfoRecord, WeaponResonanceRecord
from backend.app.db.models.player_items import InventoryItemRecord, InventoryListResponse
from backend.app.db.models.player_profile import PlayerProfileRecord, UpdatePlayerProfilePayload
