import './accounts/accounts.js';
import './accounts/account-modals.js';
import './shared/character-shared.js';
import './character/character-management.js';
import './character/character-add-modal.js';
import './shared/equip-detail-shared.js';
import './shared/equip-resonance-shared.js';
import './item/item-management.js';
import './stage/stage-management.js';
import './stage/stage-skip-modal.js';
import './memory/memory-management.js';
import './weapon/weapon-management.js';
import './character/character-weapon-switch.js';
import './character/character-memory-switch.js';
import './item/item-add-modal.js';
import './memory/memory-add-modal.js';
import './weapon/weapon-add-modal.js';
import './shared/item-modals.js';
import './player-profile/player-profile.js';
import './player-profile/portrait-picker.js';

import { initDatabaseAccountsFeature } from './accounts/accounts.js';
import { initDatabaseAccountModalFeature } from './accounts/account-modals.js';
import { initDatabaseCharacterManagementFeature } from './character/character-management.js';
import { initDatabaseCharacterAddModalFeature } from './character/character-add-modal.js';
import { initDatabaseEquipResonanceSharedFeature } from './shared/equip-resonance-shared.js';
import { initDatabaseItemManagementFeature } from './item/item-management.js';
import { initDatabaseStageManagementFeature } from './stage/stage-management.js';
import { initDatabaseStageSkipModalFeature } from './stage/stage-skip-modal.js';
import { initDatabaseMemoryManagementFeature } from './memory/memory-management.js';
import { initDatabaseWeaponManagementFeature } from './weapon/weapon-management.js';
import { initDatabaseCharacterWeaponSwitchFeature } from './character/character-weapon-switch.js';
import { initDatabaseCharacterMemorySwitchFeature } from './character/character-memory-switch.js';
import { initDatabaseItemAddModalFeature } from './item/item-add-modal.js';
import { initDatabaseMemoryAddModalFeature } from './memory/memory-add-modal.js';
import { initDatabaseWeaponAddModalFeature } from './weapon/weapon-add-modal.js';
import { initDatabaseItemModalFeature } from './shared/item-modals.js';
import { initDatabasePlayerProfileFeature } from './player-profile/player-profile.js';
import { initDatabasePortraitPickerFeature } from './player-profile/portrait-picker.js';

export const initDatabaseFeature = () => {
  initDatabaseAccountsFeature();
  initDatabaseAccountModalFeature();
  initDatabaseCharacterManagementFeature();
  initDatabaseCharacterAddModalFeature();
  initDatabaseEquipResonanceSharedFeature();
  initDatabaseItemManagementFeature();
  initDatabaseStageManagementFeature();
  initDatabaseStageSkipModalFeature();
  initDatabaseMemoryManagementFeature();
  initDatabaseWeaponManagementFeature();
  initDatabaseCharacterWeaponSwitchFeature();
  initDatabaseCharacterMemorySwitchFeature();
  initDatabaseItemAddModalFeature();
  initDatabaseMemoryAddModalFeature();
  initDatabaseWeaponAddModalFeature();
  initDatabaseItemModalFeature();
  initDatabasePlayerProfileFeature();
  initDatabasePortraitPickerFeature();
};
